-- MySQL Script generated by MySQL Workbench
-- vie 13 nov 2020 13:52:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Viveros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Viveros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Viveros` ;
USE `Viveros` ;

-- -----------------------------------------------------
-- Table `Viveros`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Vivero` (
  `CordenadaX` INT NOT NULL,
  `CordenadaY` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CordenadaX`, `CordenadaY`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viveros`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Zona` (
  `CodZona` INT NOT NULL AUTO_INCREMENT,
  `CordenadaXVivero` INT NOT NULL,
  `CordenadaYVivero` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodZona`, `CordenadaXVivero`, `CordenadaYVivero`),
  INDEX `Vivero_idx` (`CordenadaXVivero` ASC, `CordenadaYVivero` ASC),
  UNIQUE INDEX `CodZona_UNIQUE` (`CodZona` ASC),
  CONSTRAINT `Vivero`
    FOREIGN KEY (`CordenadaXVivero` , `CordenadaYVivero`)
    REFERENCES `Viveros`.`Vivero` (`CordenadaX` , `CordenadaY`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viveros`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Producto` (
  `CodigoDeBarras` INT NOT NULL,
  `CordenadaXVivero` INT NOT NULL,
  `CordenadaYVivero` INT NOT NULL,
  `CodZona` INT NOT NULL,
  `TipoDeProducto` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `Stock` INT NOT NULL,
  `Precio` INT NOT NULL,
  PRIMARY KEY (`CodigoDeBarras`, `CordenadaXVivero`, `CordenadaYVivero`, `CodZona`),
  INDEX `ZonaProducto_idx` (`CordenadaXVivero` ASC, `CordenadaYVivero` ASC, `CodZona` ASC),
  CONSTRAINT `ZonaProducto`
    FOREIGN KEY (`CordenadaXVivero` , `CordenadaYVivero` , `CodZona`)
    REFERENCES `Viveros`.`Zona` (`CordenadaXVivero` , `CordenadaYVivero` , `CodZona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viveros`.`Cliente_Fidelizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Cliente_Fidelizado` (
  `CodFidelizacion` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(70) NOT NULL,
  `VolumenMensual` INT NOT NULL,
  `Bonificaciones` INT NOT NULL,
  `FechaNacimiento` DATE NULL,
  PRIMARY KEY (`CodFidelizacion`),
  UNIQUE INDEX `CodFidelizacion_UNIQUE` (`CodFidelizacion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viveros`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Empleado` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(70) NOT NULL,
  `Puesto_Tarea` VARCHAR(45) NOT NULL,
  `Salario` INT NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viveros`.`Empleado_Zona_Trabaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Empleado_Zona_Trabaja` (
  `DNI` VARCHAR(7) NOT NULL,
  `CordenadaXVivero` INT NOT NULL,
  `CordenadaYVivero` INT NOT NULL,
  `CodZona` INT NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NOT NULL,
  PRIMARY KEY (`DNI`, `CordenadaXVivero`, `CordenadaYVivero`, `CodZona`, `FechaInicio`, `FechaFin`),
  INDEX `Zona_Trabaja_idx` (`CordenadaXVivero` ASC, `CordenadaYVivero` ASC, `CodZona` ASC),
  CONSTRAINT `Empleado_trabaja`
    FOREIGN KEY (`DNI`)
    REFERENCES `Viveros`.`Empleado` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `Zona_Trabaja`
    FOREIGN KEY (`CordenadaXVivero` , `CordenadaYVivero` , `CodZona`)
    REFERENCES `Viveros`.`Zona` (`CordenadaXVivero` , `CordenadaYVivero` , `CodZona`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viveros`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Pedido` (
  `CodPedido` INT NOT NULL AUTO_INCREMENT,
  `CodClienteFidelizado,` INT NULL,
  `DNIEmpleado` VARCHAR(9) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Importe` INT NOT NULL,
  PRIMARY KEY (`CodPedido`),
  UNIQUE INDEX `CodProducto_UNIQUE` (`CodPedido` ASC),
  INDEX `Cliente_Pedio_idx` (`CodClienteFidelizado,` ASC),
  INDEX `Empleado_Pedido_idx` (`DNIEmpleado` ASC),
  CONSTRAINT `Cliente_Pedio`
    FOREIGN KEY (`CodClienteFidelizado,`)
    REFERENCES `Viveros`.`Cliente_Fidelizado` (`CodFidelizacion`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Empleado_Pedido`
    FOREIGN KEY (`DNIEmpleado`)
    REFERENCES `Viveros`.`Empleado` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viveros`.`Producto_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Producto_Pedido` (
  `CodPedido` INT NOT NULL,
  `CodDeBarras` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `PrecioUnidad` INT NOT NULL,
  PRIMARY KEY (`CodPedido`, `CodDeBarras`),
  INDEX `ProductoDelPedido_idx` (`CodDeBarras` ASC),
  CONSTRAINT `ProductoDelPedido`
    FOREIGN KEY (`CodDeBarras`)
    REFERENCES `Viveros`.`Producto` (`CodigoDeBarras`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `Pedido`
    FOREIGN KEY (`CodPedido`)
    REFERENCES `Viveros`.`Pedido` (`CodPedido`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
